-- AlterTable
ALTER TABLE `ticket` MODIFY `status` ENUM('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'ON_HOLD', 'WORK_COMPLETED', 'RESOLVED', 'TERMINATED', 'CLOSED', 'REJECTED') NOT NULL DEFAULT 'OPEN';

-- AlterTable
ALTER TABLE `ticketstatushistory` MODIFY `status` ENUM('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'ON_HOLD', 'WORK_COMPLETED', 'RESOLVED', 'TERMINATED', 'CLOSED', 'REJECTED') NOT NULL;
