import { Response } from "express";
import prisma from "../../../prismaClient";
import { AuthenticatedRequest } from "../../../middleware/authMiddleware";
import { logAction } from "../../audit-trail/audit-trail.controller";

async function generateJENumber(): Promise<string> {
  const now = new Date();
  const month = now.getMonth() + 1;
  const fyStart = month >= 4 ? now.getFullYear() : now.getFullYear() - 1;
  const fyEnd = fyStart + 1;
  const fy = `FY${fyStart}-${(fyEnd % 100).toString().padStart(2, "0")}`;
  const latest = await prisma.journalEntry.findFirst({
    where: { entryNo: { startsWith: `JE-${fy}` } },
    orderBy: { id: "desc" },
  });
  let seq = 1;
  if (latest) {
    const parts = latest.entryNo.split("-");
    const last = parseInt(parts[parts.length - 1], 10);
    if (!isNaN(last)) seq = last + 1;
  }
  return `JE-${fy}-${seq.toString().padStart(3, "0")}`;
}

// GET /
export const getAllJournalEntries = async (req: AuthenticatedRequest, res: Response) => {
  try {
    const { isAutoGenerated, page, limit: lim, fromDate, toDate } = req.query;
    const where: any = {};
    if (isAutoGenerated !== undefined) where.isAutoGenerated = isAutoGenerated === "true";
    if (fromDate || toDate) {
      where.entryDate = {};
      if (fromDate) where.entryDate.gte = new Date(String(fromDate));
      if (toDate) where.entryDate.lte = new Date(String(toDate));
    }

    const pageNum = page ? parseInt(String(page)) : 1;
    const take = lim ? parseInt(String(lim)) : 20;
    const skip = (pageNum - 1) * take;

    const [total, entries] = await Promise.all([
      prisma.journalEntry.count({ where }),
      prisma.journalEntry.findMany({
        where,
        include: {
          createdBy: { select: { id: true, name: true } },
          purchaseVoucher: { select: { id: true, voucherNo: true } },
          paymentVoucher: { select: { id: true, voucherNo: true } },
          _count: { select: { lines: true } },
        },
        orderBy: { id: "desc" },
        skip,
        take,
      }),
    ]);
    res.json({ data: entries, total, page: pageNum, limit: take });
  } catch (err) {
    console.error(err);
    res.status(500).json({ message: "Failed to fetch journal entries" });
  }
};

// GET /:id
export const getJournalEntryById = async (req: AuthenticatedRequest, res: Response) => {
  try {
    const id = parseInt(req.params.id);
    const entry = await prisma.journalEntry.findUnique({
      where: { id },
      include: {
        lines: {
          include: {
            debitAccount: { select: { id: true, code: true, name: true } },
            creditAccount: { select: { id: true, code: true, name: true } },
          },
        },
        createdBy: { select: { id: true, name: true, employeeID: true } },
        purchaseVoucher: { select: { id: true, voucherNo: true } },
        paymentVoucher: { select: { id: true, voucherNo: true } },
      },
    });
    if (!entry) { res.status(404).json({ message: "Journal entry not found" }); return; }
    res.json(entry);
  } catch (err) {
    console.error(err);
    res.status(500).json({ message: "Failed to fetch journal entry" });
  }
};

// POST /
export const createJournalEntry = async (req: AuthenticatedRequest, res: Response) => {
  try {
    const user = (req as any).user;
    const { entryDate, narration, purchaseVoucherId, paymentVoucherId, lines } = req.body;

    if (!entryDate || !lines || !Array.isArray(lines) || lines.length === 0) {
      res.status(400).json({ message: "entryDate and lines[] are required" }); return;
    }

    // Validate that total debits == total credits
    const totalDebit = lines.reduce((s: number, l: any) => l.debitAccountId ? s + parseFloat(l.amount) : s, 0);
    const totalCredit = lines.reduce((s: number, l: any) => l.creditAccountId ? s + parseFloat(l.amount) : s, 0);
    if (Math.abs(totalDebit - totalCredit) > 0.01) {
      res.status(400).json({ message: `Total debits (${totalDebit}) must equal total credits (${totalCredit})` }); return;
    }

    const entryNo = await generateJENumber();
    const entry = await prisma.journalEntry.create({
      data: {
        entryNo,
        entryDate: new Date(entryDate),
        narration: narration ?? null,
        isAutoGenerated: false,
        totalAmount: totalDebit,
        purchaseVoucherId: purchaseVoucherId ? Number(purchaseVoucherId) : null,
        paymentVoucherId: paymentVoucherId ? Number(paymentVoucherId) : null,
        createdById: user?.employeeDbId ?? null,
        lines: {
          create: lines.map((l: any) => ({
            debitAccountId: l.debitAccountId ? Number(l.debitAccountId) : null,
            creditAccountId: l.creditAccountId ? Number(l.creditAccountId) : null,
            amount: parseFloat(l.amount),
            narration: l.narration ?? null,
          })),
        },
      } as any,
      include: { lines: true },
    });

    logAction({ entityType: "JOURNAL_ENTRY", entityId: entry.id, action: "CREATE", description: `Journal entry ${entryNo} created`, performedById: user?.employeeDbId });
    res.status(201).json(entry);
  } catch (err) {
    console.error(err);
    res.status(500).json({ message: "Failed to create journal entry" });
  }
};

// GET /ledger?accountId=&fromDate=&toDate=
export const getAccountLedger = async (req: AuthenticatedRequest, res: Response) => {
  try {
    const { accountId, fromDate, toDate } = req.query;
    if (!accountId) { res.status(400).json({ message: "accountId is required" }); return; }

    const accId = Number(accountId);
    const dateFilter: any = {};
    if (fromDate) dateFilter.gte = new Date(String(fromDate));
    if (toDate) dateFilter.lte = new Date(String(toDate));

    const account = await prisma.chartOfAccount.findUnique({ where: { id: accId } });
    if (!account) { res.status(404).json({ message: "Account not found" }); return; }

    const debitLines = await prisma.journalEntryLine.findMany({
      where: { debitAccountId: accId, journalEntry: Object.keys(dateFilter).length ? { entryDate: dateFilter } : undefined },
      include: { journalEntry: { select: { entryNo: true, entryDate: true, narration: true } } },
    });
    const creditLines = await prisma.journalEntryLine.findMany({
      where: { creditAccountId: accId, journalEntry: Object.keys(dateFilter).length ? { entryDate: dateFilter } : undefined },
      include: { journalEntry: { select: { entryNo: true, entryDate: true, narration: true } } },
    });

    const totalDebits = debitLines.reduce((s, l) => s + Number(l.amount), 0);
    const totalCredits = creditLines.reduce((s, l) => s + Number(l.amount), 0);

    res.json({
      account,
      debitLines,
      creditLines,
      totalDebits,
      totalCredits,
      balance: totalDebits - totalCredits,
    });
  } catch (err) {
    console.error(err);
    res.status(500).json({ message: "Failed to fetch account ledger" });
  }
};
